# Generated by Django 6.0.5 on 2026-05-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hates',
            field=models.IntegerField(default=0),
        ),
    ]
